### PR TITLE
feat: valiy revamp with proper types

### PR DESCRIPTION
**Pull request by pavan-bharatpe**

### CODE REVIEW

**Comment by pavan-bharatpe** [comment]
Screenshot 2022-08-29 at 12 53 17 PM

**Comment by pavan-bharatpe** [comment]
Screenshot 2022-08-30 at 11 13 42 PM

**Review by krishpe — APPROVED** [review]
LGTM Approved

**Comment by pavan-bharatpe** [comment]
Screenshot 2022-08-30 at 11 18 00 PM
Screenshot 2022-08-30 at 11 17 47 PM
Screenshot 2022-08-30 at 11 17 36 PM

**Pull request merged**
